# Generated by Django 4.1.5 on 2023-01-16 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('person_count', models.IntegerField()),
                ('is_online', models.BooleanField()),
                ('add_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField()),
                ('meeting_date', models.DateTimeField(default=datetime.datetime(2023, 1, 16, 22, 20, 59, 782503))),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
    ]
