# Generated by Django 4.1.5 on 2023-01-20 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_game_accept_date_game_accepted_by_game_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='accepted_by',
            new_name='accepted_by_id',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='requested_by',
            new_name='requested_by_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_date', models.JSONField()),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_id', to='backend.meeting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants_id',
            field=models.ManyToManyField(through='backend.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
