# Generated by Django 4.1.5 on 2023-01-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_accepted_by_game_accepted_by_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='meeting_date',
        ),
    ]
