# Generated by Django 4.1.5 on 2023-01-20 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_remove_participant_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants_id',
            field=models.ManyToManyField(related_name='participants_id', through='backend.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
