# Generated by Django 4.1.5 on 2023-01-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_participant_prefered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='prefered_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
