# Generated by Django 4.1.5 on 2023-01-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_participant_prefered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
